build:
    image: latest

formats:
    - epub

python:
    extra_requirements:
        - cli
        - colour
        - iso_8601
        - net
        - template
    pip_install: true
    version: 3

requirements_file:
    extra/requirements-doc.txt
