version: 2
python:
  install:
   - requirements: extra/requirements-doc.txt
   - method: pip
     path: .
     extra_requirements:
       - cli
       - colour
       - iso_8601
       - template
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
